In [1]:
import numpy as np

In [31]:
l1 = [1,"abc",2.5]
l1

[1, 'abc', 2.5]

In [32]:
type(l1[2])

float

In [4]:
#create numpy array

arr = np.array([10,5,20,15])
arr

array([10,  5, 20, 15])

In [5]:
#create numpy array

mix_arr = np.array([10,20,3.5,'hello'])
mix_arr

array(['10', '20', '3.5', 'hello'], dtype='<U32')

In [6]:
type(mix_arr)

numpy.ndarray

In [7]:
type(mix_arr[1])

numpy.str_

In [33]:
#multi-dimensional array

m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(m[0][1])

numpy.int32

In [10]:
m[0][1]

2

In [11]:
#multi-dimensional array

m1 = np.array([[1,2,3],
             [4,5,6]], np.int32)
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
type(m1)

numpy.ndarray

In [13]:
import  numpy as np
myarr=np.array([[1,2,3,4],[1,2,5,6],[1,3,4,5]])
print(myarr)


[[1 2 3 4]
 [1 2 5 6]
 [1 3 4 5]]


In [14]:
print(myarr.flatten()) #combines all the elements of array

[1 2 3 4 1 2 5 6 1 3 4 5]


In [15]:
print(np.max(myarr)) #finding max value from matrix
print(np.min(myarr)) #fining min value from matrix
print(np.sum(myarr)) #calculating sum of all the values of matrix
print(np.max(myarr,axis=0)) #finding max value column wise
print(np.min(myarr,axis=0)) #fining min value column wise
print(np.sum(myarr,axis=0)) #calculating sum column wise
print(np.max(myarr,axis=1)) #finding max value row wise
print(np.min(myarr,axis=1)) #fining min value row wise
print(np.sum(myarr,axis=1)) #calculating sum row wise
print(myarr.dtype) #check data type
print(myarr.shape) #no. of rows and columns
print(myarr.size) #total no. of elements

6
1
37
[1 3 5 6]
[1 2 3 4]
[ 3  7 12 15]
[4 6 5]
[1 1 1]
[10 14 13]
int32
(3, 4)
12


In [16]:
print(myarr.T) #Transpose matrix

[[1 1 1]
 [2 2 3]
 [3 5 4]
 [4 6 5]]


In [17]:
print(myarr)

[[1 2 3 4]
 [1 2 5 6]
 [1 3 4 5]]


In [18]:
print(myarr[0:2,0:])

[[1 2 3 4]
 [1 2 5 6]]


In [19]:
print(myarr[2,:])

[1 3 4 5]


In [20]:
print(myarr[:1,2])

[3]


In [21]:
newarr=np.ones((2,3)) #by default data type "float"
print(newarr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
newarr=np.ones((2,3),dtype = np.int32)
print(newarr)

[[1 1 1]
 [1 1 1]]


In [23]:
mat2 = np.zeros([5,5])
print(mat2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [34]:
newarr1=np.empty((2,2),dtype = np.int32)
newarr1

array([[135829216,       591],
       [        0,         0]])

In [25]:
n_eye = np.eye(6,dtype=np.int32)
n_eye

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [26]:
even = np.arange(2,24,2)
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [27]:
f = np.arange(1,3,0.2)
f

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [28]:
np.arange(8) #it will create array of elements from 0 to 7

array([0, 1, 2, 3, 4, 5, 6, 7])

In [29]:
arnd = np.arange(8).reshape(2,4) # total 8 elements will be shaped into 2 rows and 4 columns
arnd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [36]:
arnd = np.arange(8).reshape(3,3) # total 8 elements required - here only 6 elements are there
arnd

ValueError: cannot reshape array of size 8 into shape (3,3)

In [37]:
arnd = np.arange(6).reshape(2,3)
arnd

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
x = np.array([[1,2],[3,4]]) #x = np.array([1,2,3,4]
y = np.array([[3,5],[1,4]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[3 5]
 [1 4]]


In [39]:
x+y

array([[4, 7],
       [4, 8]])

In [40]:
x-y

array([[-2, -3],
       [ 2,  0]])

In [41]:
x*y#this is not the correct matrix multiplication

array([[ 3, 10],
       [ 3, 16]])

In [ ]:
#actual multiplication of matrices
np.dot(x,y)

In [42]:
m = np.pi
m

3.141592653589793

In [43]:
a = np.array([0,30,60,90,120,150,180])
ar = a * np.pi/180
ar

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265])

In [44]:
print("sine value : ",np.sin(ar))
print("cosine value : ",np.cos(ar))
print("tangent value : ",np.tan(ar))

sine value :  [0.00000000e+00 5.00000000e-01 8.66025404e-01 1.00000000e+00
 8.66025404e-01 5.00000000e-01 1.22464680e-16]
cosine value :  [ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00]
tangent value :  [ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16]


In [45]:
np.exp(4) #e^x

54.598150033144236

In [46]:
np.sqrt(4)

2.0

In [49]:
x=np.arange(10)
x
#np.sqrt(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
print(np.mean(x))
print(np.median(x))
print(np.var(x))
print(np.std(x))

4.5
4.5
8.25
2.8722813232690143


In [51]:
x=np.arange(5) ** 2
x

array([ 0,  1,  4,  9, 16])

In [52]:
np.power(2,3)

8

In [53]:
y=np.append(x,20)
y

array([ 0,  1,  4,  9, 16, 20])

In [54]:
y=np.insert(x,2,30)
y

array([ 0,  1, 30,  4,  9, 16])

In [55]:
z=np.sort(y)
z

array([ 0,  1,  4,  9, 16, 30])

In [56]:
z[::-1]

array([30, 16,  9,  4,  1,  0])

In [59]:
random_num = np.random.randint(1,11) #generate anyone random integer value
random_num

2

In [ ]:
ran_float = np.random.rand() #generate random float value between 0 and 1
ran_float

In [ ]:
ran_float_range=np.random.uniform(1,5)#generate random float value between 1 to 5
ran_float_range

In [ ]:
#generate random numbers from normal distribution with mean 0 and standard deviation 1
rnd = np.random.normal(0,1,size=(3,3))
rnd

In [62]:
np.random.seed(4)
rnd = np.random.rand(3)
rnd

array([0.96702984, 0.54723225, 0.97268436])

In [63]:
rand_vec = np.random.randn(15)

print(rand_vec)
print()
print(rand_vec>0)

[ 0.9934697   1.07932256  1.45162561 -0.33881198  0.36623181 -0.30501214
 -0.48492332 -0.12066567 -0.0788265   0.56373477 -0.18040236  0.20218012
  0.16951775 -0.71522547  0.52533388]

[ True  True  True False  True False False False False  True False  True
  True False  True]


In [ ]:
rand_vec = np.random.randn(19)
print(rand_vec)
print()
print(rand_vec[6])

In [64]:
rand_mat4 = np.random.rand(5,5) # uniform random variable
print(rand_mat4)

[[0.40844386 0.52790882 0.93757158 0.52169612 0.10819338]
 [0.15822341 0.54520265 0.52440408 0.63761024 0.40149544]
 [0.64980511 0.3969     0.62391611 0.76740497 0.17897391]
 [0.37557577 0.50253306 0.68666708 0.25367965 0.55474086]
 [0.62493084 0.89550117 0.36285359 0.63755707 0.1914464 ]]
